formats:
    - epub
    - pdf
# requirements_file: (pip requirements)
#    requirements/docs.txt
# conda: (conda requirements)
#    file: environment.yml 
python:
#    setup_py_install: true  # use setup.py to include module itself
    pip_install: true  # use pip install -e to include module itself
    extra_requirements:
        - matplotlib
        - pandas
